name : Tags
version : $version
main : broccolai.tags.bukkit.BukkitTagsPlatform
loader: broccolai.tags.bukkit.PaperTagsLoader
api-version : '1.20'
dependencies:
    server:
        Vault:
            load: BEFORE
            required: true
            join-classpath: true
softdepend : [ PlaceholderAPI ]
permissions :
  tags.user :
    default : true
    description : Permissions needed for users
    children :
      tags.command.user : true
  tags.staff :
    default : op
    description : Permissions needed for staff
    children :
      tags.command.staff : true
  tags.command.user :
    default : true
    children :
      tags.command.user.select : true
      tags.command.user.list : true
      tags.command.user.info : true
  tags.command.admin :
    default : op
    children :
      tags.command.admin.give : true
      tags.command.admin.remove : true
      tags.command.admin.list : true
