object Versions {
    const val INDRA = "3.0.1"
    const val SHADOW = "7.1.2"

    const val GUAVA = "21.0"
    const val SPIGOT = "1.19.2-R0.1-SNAPSHOT"
    const val PAPI = "2.11.2"
    const val VAULT = "1.7.1"
    const val GUICE = "5.1.0"
    const val JDBI = "3.34.0"
    const val HIKARI = "5.0.1"
    const val FLYWAY = "9.8.1"
    const val CONFIGURATE = "4.1.2"
    const val CORN = "2.2.0"
    const val ADVENTURE = "4.11.0"
    const val ADVENTURE_PLATFORM = "4.1.2"
    const val EVENT = "4.0.0-SNAPSHOT"
    const val COFFEE = "1.0.0-SNAPSHOT"
    const val CLOUD = "1.7.1"
    const val LUCKPERMS = "5.4"
}
